# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9c9737779884a4fcc8138740cf1acd3f8d78134d6b557ef87f84df650f18cdf963dbae1164b02006cafd86d5e58387865dc8c7986dea41037e8ac82afa1704a

test:
  secret_key_base: ec13f442d53c184b923f5d8f72eedd65754cc05b79b30cd8ca0e142313401bec4fac910a4cb72b84f1e2e61b5b40b5b2d2a619fd5cb5e8b11737eaad398770d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
